aws:
  region: eu-west-1
  accessKey: testAccessKey
  secretKey: testSecretKey
  dynamodb:
    protocol: http
    host: localhost
    port: 8000
    endpoint: ${aws.dynamodb.protocol}://${aws.dynamodb.host}:${aws.dynamodb.port}
    tablePrefix: local-
